apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cgqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cgqz
    app.kubernetes.io/part-of: test-pipeline-service-ci-stage
  name: devfile-sample-cgqz
  namespace: sabhardw-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-cgqz
status:
  loadBalancer: {}
